# http://docs.haskellstack.org/en/stable/travis_ci.html

language: haskell

branches:
  only:
    - master

sudo: true

cache:
  directories:
    - $HOME/.stack/

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libbluetooth-dev
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - chmod a+x ~/.local/bin/stack

install:
  - stack setup
  - stack build --only-snapshot

script:
  - stack build --test

